#!/bin/bash

set -e -u -o pipefail

package=github.com/hansmi/wp2reg-luxws

docker run --rm \
  --user "$(id -u):$(id -g)" \
  --env HOME=/tmp \
  --env GITHUB_TOKEN=a \
  -v "${PWD}:/go/src/${package}" \
  -w "/go/src/${package}" \
  goreleaser/goreleaser:latest release --clean --snapshot

# vim: set sw=2 sts=2 et :
