# Configuration for GoReleaser
# https://goreleaser.com/

version: 2

project_name: wp2reg-luxws

builds:
  - main: ./luxws-exporter/
    binary: luxws-exporter
    env:
      - CGO_ENABLED=0
    targets:
      - go_first_class
    flags:
      - -trimpath

nfpms:
  - description: Prometheus exporter for heat pump controllers
    maintainer: M. Hanselmann
    bindir: /usr/bin
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
    contents:
      - src: ./README.md
        dst: /usr/share/doc/luxws-exporter/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/luxws-exporter/LICENSE

archives:
  - format: tar.gz
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true
  prerelease: auto

snapshot:
  version_template: '{{ incpatch .Version }}-snapshot{{ replace (replace .Date ":" "") "-" "" }}+g{{ .ShortCommit }}'

# vim: set sw=2 sts=2 et :
